Bibliotecas

In [3]:
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
import seaborn as sns

In [4]:
import statsmodels.formula.api as smf
import statsmodels.stats.api as sms

In [5]:
galapagos = pd.read_csv("dados/galapagos.csv")
galapagos.head()

   Species  Endemics   Area  Elevation  Nearest  Scruz  Adjacent
0       58        23  25.09        346      0.6    0.6      1.84
1       31        21   1.24        109      0.6   26.3    572.33
2        3         3   0.21        114      2.8   58.7      0.78
3       25         9   0.10         46      1.9   47.4      0.18
4        2         1   0.05         77      1.9    1.9    903.82

In [6]:
model = smf.ols("Species ~ Area + Elevation + Nearest + Scruz + Adjacent", data=galapagos).fit()

In [7]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                Species   R-squared:                       0.766
Model:                            OLS   Adj. R-squared:                  0.717
Method:                 Least Squares   F-statistic:                     15.70
Date:                Thu, 11 Jun 2026   Prob (F-statistic):           6.84e-07
Time:                        13:11:03   Log-Likelihood:                -162.54
No. Observations:                  30   AIC:                             337.1
Df Residuals:                      24   BIC:                             345.5
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      7.0682     19.154      0.369      0.715     -32.464      46.601
Area          -0.0239      0.022     -1.068      0.296      -0.070       0.022
Elevation      0.3195      0.054      5.953      0.000       0.209       0.430
Nearest        0.0091      1.054      0.009      0.993      -2.166       2.185
Scruz         -0.2405      0.215     -1.117      0.275      -0.685       0.204
Adjacent      -0.0748      0.018     -4.226      0.000      -0.111      -0.038
==============================================================================
Omnibus:                       12.683   Durbin-Watson:                   2.476
Prob(Omnibus):                  0.002   Jarque-Bera (JB):               13.498
Skew:                           1.136   Prob(JB):                      0.00117
Kurtosis:                       5.374   Cond. No.                     1.90e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.9e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

$$RSS = \sum_{i=1}^{n} (y_i - \hat{y}_i)^2$$

In [8]:
sms.anova_lm(model)

             df         sum_sq        mean_sq          F    PR(>F)
Area        1.0  145470.212144  145470.212144  39.126209  0.000002
Elevation   1.0   65664.304683   65664.304683  17.661315  0.000315
Nearest     1.0      29.242630      29.242630   0.007865  0.930067
Scruz       1.0   14279.853308   14279.853308   3.840762  0.061732
Adjacent    1.0   66406.387572   66406.387572  17.860909  0.000297
Residual   24.0   89231.366330    3717.973597        NaN       NaN

In [9]:
H = X@np.linalg.inv(X.T @ X)@X.T

NameError: name 'X' is not defined